Description: Provisions custom project for sagemaker.
Parameters:
  SageMakerProjectName:
    Type: String
    Description: Name of the project
    MinLength: 1
    MaxLength: 32
    AllowedPattern: "^[a-zA-Z](-*[a-zA-Z0-9])*"
  SageMakerProjectId:
    Type: String
    Description: Service generated Id of the project.
  ModelGroupDescription:
    Type: String
    Description: Description of Model
    AllowedPattern: .*
  GitUser:
    Type: String
    Description: Git user to give admin over the project repositories
  PipelineType:
    Type: String
    Description: Sagemaker Pipeline LLM training type to deploy
    AllowedValues:
      - "jumpstart-pipeline"
      - "jumpstart-pipeline-finetuning"
      - "jumpstart-pipeline-scale"
      - "jumpstart-pipeline-scale-hybrid"
      - "advanced-pipeline"
      - "advanced-pipeline-finetuning"
      - "advanced-pipeline-scale"
      - "advanced-pipeline-scale-hybrid"
    Default: "jumpstart-pipeline"
Conditions:
  AdvancedPip: !Equals
    - !Ref PipelineType
    - "advanced-pipeline"
  AdvancedPipFN: !Equals
    - !Ref PipelineType
    - "advanced-pipeline-finetuning"
  AdvancedPipSC: !Equals
    - !Ref PipelineType
    - "advanced-pipeline-scale"
  AdvancedPipSCHyb: !Equals
    - !Ref PipelineType
    - "advanced-pipeline-scale-hybrid"
  JSPip: !Equals
    - !Ref PipelineType
    - "jumpstart-pipeline"
  JSPipFN: !Equals
    - !Ref PipelineType
    - "jumpstart-pipeline-finetuning"
  JSPipSC: !Equals
    - !Ref PipelineType
    - "jumpstart-pipeline-scale"
  JSPipSCHyb: !Equals
    - !Ref PipelineType
    - "jumpstart-pipeline-scale-hybrid"
  
Resources:
  MlOpsArtifactsBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub >-
        mlops-${SageMakerProjectName}-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
      VersioningConfiguration:
        Status: Enabled

  MLOpsModelPackageGroup:
    Type: "AWS::SageMaker::ModelPackageGroup"
    Properties:
      ModelPackageGroupName: !Sub "${SageMakerProjectName}-${SageMakerProjectId}"
      ModelPackageGroupDescription: !Ref ModelGroupDescription
      Tags:
        - Key: "sagemaker:project-name"
          Value: !Sub "${SageMakerProjectName}"
        - Key: "sagemaker:project-id"
          Value: !Sub "${SageMakerProjectId}"
  PipelineProductUseRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - sagemaker.amazonaws.com
            Action: "sts:AssumeRole"
      Description: Role to use for launching the SageMaker Project
      ManagedPolicyArns:
        - "{{resolve:ssm:arn_sagemaker_execution_policy}}"
        - "{{resolve:ssm:arn_sagemaker_related_policy}}"
        - "{{resolve:ssm:arn_sagemaker_pass_role_policy}}"
        - "{{resolve:ssm:arn_sagemaker_s3_policy}}"
        - "{{resolve:ssm:arn_sagemaker_vpc_policy}}"
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        #- "{{resolve:ssm:arn_deny_sagemaker_jobs_outside_vpc}}"
      Policies:
        - PolicyName: sagemaker_s3_service_catalog_bucket
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "s3:Get*"
                  - "s3:Put*"
                Resource:
                  - !Sub "arn:aws:s3:::${MlOpsArtifactsBucket}/*"
                  - !Sub "arn:aws:s3:::${MlOpsArtifactsBucket}"
              - Effect: Deny
                Action:
                  - "sagemaker:DeleteModelPackage"
                  - "sagemaker:DeleteModelPackageGroup"
                Resource:
                  - !Sub >-
                    arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:model-package-group/*
                  - !Sub >-
                    arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:model-package/*
              - Effect: Allow
                Action:
                  - "sagemaker:AddTags"
                Resource:
                  - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:experiment-trial-component/*"
                  - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:experiment-trial/*"
                  - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:experiment/*"
                  - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:model/*"
                  - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:pipeline/*"
                  - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:processing-job/*"
                  - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:project/*"
                  - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:training-job/*"
                  - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:transform-job/*"
              - Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:*"
              - Effect: Allow
                Action:
                  - "ssm:GetParameter"
                Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/*"

  CustomResourceLambdaRepoBuild:
    Type: "Custom::LambdaCloneRepoBuild"
    Properties:
      GIT_USER: !Ref GitUser
      ORGANIZATION: "{{resolve:ssm:github_organization}}"
      REPO_NAME: !Sub "mlops-${SageMakerProjectName}-${SageMakerProjectId}-llm-training"
      VAR_ARTIFACT_BUCKET: !Ref MlOpsArtifactsBucket
      VAR_AWS_REGION: !Ref "AWS::Region"
      VAR_SAGEMAKER_PIPELINE_ROLE_ARN: !GetAtt PipelineProductUseRole.Arn
      VAR_SAGEMAKER_PROJECT_ARN: !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:project/${SageMakerProjectName}"
      VAR_SAGEMAKER_PROJECT_ID: !Ref SageMakerProjectId
      VAR_SAGEMAKER_PROJECT_NAME_ID: !Sub "${SageMakerProjectName}-${SageMakerProjectId}"
      VAR_SAGEMAKER_PROJECT_NAME: !Ref SageMakerProjectName
      VAR_PIPELINE_TYPE: !If
        - JSPip
        - "sm_pipelines"
        - !If 
          - JSPipFN
          - "sm_pipelines"
          - !If 
            - JSPipSC
            - "sm_pipelines"
            -  !If 
              - JSPipSCHyb
              - "sm_pipelines"
              - "sm_pipelines_advanced"
      VAR_PIPELINE: !If
        - JSPip
        - "pipeline.py"
        - !If 
          - JSPipFN
          - "pipeline_finetuning.py"
          - !If 
            - JSPipSC
            - "pipeline_scale.py"
            -  !If 
              - JSPipSCHyb
              - "pipeline_scale.py"
              - "pipeline_scale_advanced.py"            
      VAR_PIPELINE_CONFIG: !If
        - JSPip
        - "pipeline_config.yaml"
        - !If 
          - JSPipFN
          - "pipeline_finetuning_config.yaml"
          - !If 
            - JSPipSC
            - "pipeline_scale_config.yaml"
            -  !If 
              - JSPipSCHyb
              - "pipeline_scale_hybrid_config.yaml"
              - !If 
                - AdvancedPip
                - "pipeline_config.yaml"
                - !If 
                    - AdvancedPipFN
                    - "pipeline_finetuning_config.yaml"
                    - !If 
                      - AdvancedPipSC
                      - "pipeline_scale_config.yaml"
                      - "pipeline_scale_hybrid_config.yaml"
      SECRET_AWS_DEV_ACCOUNT_NUMBER: !Ref "AWS::AccountId"
      ServiceToken: "{{resolve:ssm:arn_clone_repo_lambda}}"
      TEMPLATE_REPO: "{{resolve:ssm:github_llm_repo_template}}"

  ModelBuildSagemakerCodeRepository:
    Type: "AWS::SageMaker::CodeRepository"
    DependsOn: CustomResourceLambdaRepoBuild
    Properties:
      CodeRepositoryName: !Sub "aws-mlops-${SageMakerProjectName}-llm-training"
      GitConfig:
        Branch: main
        RepositoryUrl: !Sub "https://github.com/{{resolve:ssm:github_organization}}/mlops-${SageMakerProjectName}-${SageMakerProjectId}-llm-training.git"
      Tags:
        - Key: "sagemaker:project-id"
          Value: !Sub ${SageMakerProjectId}
        - Key: "sagemaker:project-name"
          Value: !Sub ${SageMakerProjectName}
